### ISSUE TITLE
Not Enterprise: please rewrite in Java

### ISSUE THREAD

**Issue by travisbrady** [pm3310/pulpo#5]
This repository is written in "python" a very cute toy language, but not ready for PRODUCTION use in BIG COMPANIES that make REAL MONEY.

Example of cute python code:
```python
true = True
for NUM in range(5):
    for OTHER_NUM in range(5):
        if NUM > 0 and OTHER_NUM > 0 and true is True:
            print("yay Python is so cute lol 😃" + str(NUM) + "{}".format(true) + " " + "%s" % ("hi"))
```

See. The code above is obviously garbage and python language is the reason why. 
Please do the right thing and rewrite in scalable enterprise language.

**Comment by pm3310** [comment]
We'll re-write it in C!
